version: 2

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements/discordpy.txt
    - method: pip
      path: .
    - requirements: requirements/docs.txt
    - requirements: requirements/procinfo.txt
    - requirements: requirements/voice.txt
